import { Car } from './types';

export const mockCars: Car[] = [
{
  id: '1',
  make: 'Toyota',
  model: 'Camry',
  year: 2024,
  category: 'Compact',
  pricePerDay: 65,
  transmission: 'Automatic',
  fuelType: 'Hybrid',
  seats: 5,
  rating: 4.8,
  reviewCount: 312,
  fuelEfficiency: 52,
  location: 'New York',
  available: true,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1868ff5f6-1772638689088.png",
  alt: 'Silver Toyota Camry sedan parked on clean urban street with city buildings in background',
  features: ['GPS', 'Bluetooth', 'Backup Camera'],
  badge: 'Best Seller'
},
{
  id: '2',
  make: 'Ford',
  model: 'Explorer',
  year: 2024,
  category: 'SUV',
  pricePerDay: 95,
  transmission: 'Automatic',
  fuelType: 'Petrol',
  seats: 7,
  rating: 4.7,
  reviewCount: 245,
  fuelEfficiency: 28,
  location: 'Los Angeles',
  available: true,
  image: "https://images.unsplash.com/photo-1665611744289-4141bfd2618a",
  alt: 'White Ford Explorer SUV parked on open road with mountains in the background',
  features: ['GPS', 'Sunroof', 'Third Row Seating', 'Apple CarPlay'],
  badge: 'Family Pick'
},
{
  id: '3',
  make: 'Tesla',
  model: 'Model 3',
  year: 2024,
  category: 'Electric',
  pricePerDay: 120,
  transmission: 'Automatic',
  fuelType: 'Electric',
  seats: 5,
  rating: 4.9,
  reviewCount: 189,
  fuelEfficiency: 130,
  location: 'San Francisco',
  available: true,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1758583a3-1769221139172.png",
  alt: 'Red Tesla Model 3 electric sedan on highway with clear blue sky overhead',
  features: ['Autopilot', 'Supercharging', 'Premium Sound', 'Glass Roof'],
  badge: 'Eco Choice'
},
{
  id: '4',
  make: 'BMW',
  model: '5 Series',
  year: 2023,
  category: 'Luxury',
  pricePerDay: 175,
  transmission: 'Automatic',
  fuelType: 'Petrol',
  seats: 5,
  rating: 4.8,
  reviewCount: 134,
  fuelEfficiency: 32,
  location: 'New York',
  available: true,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c4d9335f-1770501057882.png",
  alt: 'Black BMW 5 Series luxury sedan on a wet city street at night with reflections',
  features: ['Leather Seats', 'Heads-Up Display', 'Parking Assist', 'Ambient Lighting'],
  badge: 'Premium'
},
{
  id: '5',
  make: 'Honda',
  model: 'Civic',
  year: 2024,
  category: 'Economy',
  pricePerDay: 45,
  transmission: 'Manual',
  fuelType: 'Petrol',
  seats: 5,
  rating: 4.5,
  reviewCount: 421,
  fuelEfficiency: 38,
  location: 'Chicago',
  available: true,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f9fef6f8-1772300768504.png",
  alt: 'Blue Honda Civic compact car parked in suburban neighborhood on sunny day',
  features: ['Bluetooth', 'Backup Camera', 'Lane Assist']
},
{
  id: '6',
  make: 'Chevrolet',
  model: 'Traverse',
  year: 2023,
  category: 'Van',
  pricePerDay: 110,
  transmission: 'Automatic',
  fuelType: 'Petrol',
  seats: 8,
  rating: 4.6,
  reviewCount: 98,
  fuelEfficiency: 25,
  location: 'Miami',
  available: false,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1cb38ba11-1773157627350.png",
  alt: 'Gray Chevrolet Traverse minivan parked in parking lot showing spacious family vehicle',
  features: ['8-Passenger', 'Rear Entertainment', 'Tri-Zone Climate']
},
{
  id: '7',
  make: 'Porsche',
  model: '911',
  year: 2024,
  category: 'Sports',
  pricePerDay: 295,
  transmission: 'Automatic',
  fuelType: 'Petrol',
  seats: 2,
  rating: 4.9,
  reviewCount: 67,
  fuelEfficiency: 22,
  location: 'Las Vegas',
  available: true,
  image: "https://images.unsplash.com/photo-1697830278620-bc981ebed378",
  alt: 'Yellow Porsche 911 sports car on empty race track with dramatic lighting',
  features: ['Sport Chrono', 'PASM', 'Sport Exhaust', 'Bose Sound'],
  badge: 'Thrill Seeker'
},
{
  id: '8',
  make: 'Hyundai',
  model: 'Ioniq 6',
  year: 2024,
  category: 'Electric',
  pricePerDay: 98,
  transmission: 'Automatic',
  fuelType: 'Electric',
  seats: 5,
  rating: 4.7,
  reviewCount: 143,
  fuelEfficiency: 140,
  location: 'Seattle',
  available: true,
  image: "https://images.unsplash.com/photo-1712542982721-e8047eae3ca4",
  alt: 'White Hyundai Ioniq 6 electric sedan on coastal road with ocean view in background',
  features: ['800V Charging', 'Digital Mirrors', 'Relaxation Seats'],
  badge: 'Eco Choice'
},
{
  id: '9',
  make: 'Jeep',
  model: 'Wrangler',
  year: 2023,
  category: 'SUV',
  pricePerDay: 115,
  transmission: 'Manual',
  fuelType: 'Petrol',
  seats: 5,
  rating: 4.6,
  reviewCount: 276,
  fuelEfficiency: 20,
  location: 'Denver',
  available: true,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e0e978ee-1772126452947.png",
  alt: 'Orange Jeep Wrangler off-road SUV on rocky mountain trail with pine trees',
  features: ['4WD', 'Removable Roof', 'Off-Road Package']
},
{
  id: '10',
  make: 'Mercedes-Benz',
  model: 'E-Class',
  year: 2024,
  category: 'Luxury',
  pricePerDay: 195,
  transmission: 'Automatic',
  fuelType: 'Diesel',
  seats: 5,
  rating: 4.8,
  reviewCount: 112,
  fuelEfficiency: 40,
  location: 'New York',
  available: true,
  image: "https://images.unsplash.com/photo-1605557008584-3e8a54bdb8fb",
  alt: 'Silver Mercedes-Benz E-Class luxury sedan on tree-lined boulevard in autumn',
  features: ['MBUX', 'Burmester Sound', 'Air Suspension', 'Night Vision'],
  badge: 'Premium'
},
{
  id: '11',
  make: 'Kia',
  model: 'Sportage',
  year: 2024,
  category: 'Compact',
  pricePerDay: 72,
  transmission: 'Automatic',
  fuelType: 'Hybrid',
  seats: 5,
  rating: 4.5,
  reviewCount: 198,
  fuelEfficiency: 45,
  location: 'Houston',
  available: true,
  image: "https://images.unsplash.com/photo-1688893287585-b1bc00e608fc",
  alt: 'Dark green Kia Sportage compact SUV parked in modern urban setting',
  features: ['Panoramic Roof', 'Wireless Charging', 'Smart Cruise']
},
{
  id: '12',
  make: 'Volkswagen',
  model: 'Golf',
  year: 2023,
  category: 'Economy',
  pricePerDay: 52,
  transmission: 'Manual',
  fuelType: 'Petrol',
  seats: 5,
  rating: 4.4,
  reviewCount: 334,
  fuelEfficiency: 35,
  location: 'Boston',
  available: false,
  image: "https://images.unsplash.com/photo-1572811298995-74b11ebea596",
  alt: 'White Volkswagen Golf hatchback parked on European cobblestone street',
  features: ['Bluetooth', 'Digital Cockpit', 'Lane Keep Assist']
}];